### ISSUE TITLE
A type mismatch is reported on every enclosing form, not once on the term that is wrong

### ISSUE THREAD

**Issue by 7h3kk1d** [hazelgrove/hazel#2561]
A term whose child already reports a mismatch against its expected type is reported again itself, on every enclosing form, so one mistake produces a row of red marks running up the tree. #2507 is one instance of this. This issue is the general problem and collects the rest.

## Instances

- [ ] #2507 — function bodies
- [ ] Tuple components and labeled tuple values — no issue of its own, fixed in PR #2502
- [ ] Lists, `::` and `@` (A below)
- [ ] Sequences, `let` bodies, `typfun` bodies, `case`/`if` rule bodies (A below)
- [ ] Function parameter annotations (B below)
- [ ] `if`/`case` in analytic position (C below)

## Mechanism

A parent builds its own type out of its children's `elab_syn_ty`. When a child is already marked `ExpectationMismatch`, its `elab_syn_ty` still holds the *wrong* type, so the parent's type is wrong too, so the parent is marked against *its* expectation — and so on outwards.

The fix is known and small at each site: take the expected type for a child that has already reported, so the parent has nothing left to report. PR #2502, opened for #1958 and #2507, does this for `Tuple`, `TupLabel` and `Fun` with one line at the parent's type construction,

```reason
List.exists(Mark.is_expectation_mismatch, child.marks) ? expected : child.elab_syn_ty
```

and the remaining parents want the same treatment.

## A. Parents that rebuild their type from a child's

```
$ echo 'let xs : [Int] = ["s"] in xs' | ./hazel analyze -
Found 2 static errors:

error: Expecting type Int but got inconsistent type String
  --> -:1:19
  |
1 | let xs : [Int] = ["s"] in xs
  |                   ^^^

error: Expecting type [Int] but got inconsistent type [String]
  --> -:1:18
  |
1 | let xs : [Int] = ["s"] in xs
  |                  ^^^^^
```

Only the element is wrong. The list is marked because `ListLit` takes the meet of the elements' `elab_syn_ty`.

| Form | Example | errors | extra marks |
|---|---|---|---|
| `ListLit` | `let xs : [Int] = ["s"] in xs` | 2 | the whole list |
| `ListLit` | `let xs : [Int] = ["s", "t"] in xs` | 3 | the whole list |
| `ListLit`, nested | `let xs : [[Int]] = [[["s"]]] in xs` | 3 | one per level |
| `Cons` | `let xs : [Int] = 1 :: ["s"] in xs` | 2 | the tail list |
| `ListConcat` | `let x : [Int] = [1] @ ["s"] in x` | 2 | the operand list |
| `Seq` | `let x : Int = 1; "s" in x` | 2 | the sequence |
| `Let` body | `let x : Int = let y = "s" in y in x` | 2 | the inner `let` |
| `TypFun` body | `let x : poly a -> Int = typfun a -> "s" in x` | 2 | the `typfun` |
| `Match` rules | `let x : Int = case 1 \| 1 => "a" \| _ => "b" end in x` | 3 | the whole `case` |

`TypFun` is the exact analogue of the `Fun` case in #2507: `~elab_syn_ty=Poly(utpat, body.elab_syn_ty)`. `Seq` is `~elab_syn_ty=e2.elab_syn_ty`.

These nest, so the count is the nesting depth:

```
let x : Int = case 1 | _ => let y = "s" in y end in x    → 3 errors (case, let, y)
```

## B. Function parameter annotations

```
let x : Int -> Int = fun (y : String) -> y in x
```

Four errors on `dev` for one wrong annotation: the `fun`, the parenthesized pattern, the ascribed pattern, and the body. The first is the #2507 instance; the other three are their own.

## C. `if` / `case` in analytic position

```
$ echo 'let x : Int = if true then "s" else 2 in x' | ./hazel analyze -
Found 2 static errors:

error: (static error)
  --> -:1:15
  |
1 | let x : Int = if true then "s" else 2 in x
  |               ^^^^^^^^^^^^^^^^^^^^^

error: Expecting type Int but got inconsistent type String
  --> -:1:28
```

Both branches were analyzed against `Int`, so the `if` has nothing of its own to report: only `"s"` should be marked. Instead the branches' *synthesized* types are meet-ed against each other and the failure is reported on the whole `if` as `Mark.NoMeet(Id, _)`. Same for `case`.

Two things are wrong here:

1. The branch meet should not run in analytic position at all — when every branch has its expectation, disagreement between them is a consequence, not a separate error. (In synthetic position the check is right and its message is good: `let x = if true then 1 else "s" in x` reports *Expecting branches to have consistent types but got types: Int, String*.)
2. Even when it does fire, the message is lost. `ErrorPrint.core_mark_string` falls through `NoMeet(wrap, _tys)` to the literal string `"(static error)"` whenever `Typ.meet(ctx, ana, meet_of(wrap, ?))` succeeds, which is the analytic case. The user is told a term is wrong and nothing else.

## Not in scope: parentheses

`Parens` copies its child's marks verbatim (`~marks=e.marks`), so a mismatch inside parens is reported once per layer:

```
let x : Int = ((((("s"))))) in x    → 6 errors
```

This is deliberate — #1997 asked for parentheses to be highlighted when the term inside them has an error, and the editor wants that. But "highlight the parentheses" and "emit another entry in the error list" are not the same request, and at five layers the second one is clearly wrong. Worth thinking about separately rather than folding into this fix. `Projector` and `DynamicErrorHole` forward marks the same way.

## Caution: this interacts with #2444 / #2305

`let xs : [Int] = ["s", 1] in xs` reports **one** error, not three. The list escapes its own mark only because its elements do not meet each other, so it falls back to `[?]`, which is consistent with `[Int]`, and `should_emit_nomeet_mark` suppresses the `NoMeet` mark.

That same gate is why `[1, ""]` reports nothing at all (#2444, #2305, introduced by #2213). So the list part of this issue should not be fixed by widening the suppression — the two want fixing together: a list whose elements disagree needs its own error, and a list whose element already reported its own mismatch needs no error.

## Measured on

`dev` at `fa6cd4eb09`, via `./hazel analyze -`. Counts in the table are unchanged by PR #2502; the one it changes is B, from four errors to three.

**Comment by 7h3kk1d** [comment]
Every example in one place, measured on `dev` at `fa6cd4eb09` with `./hazel analyze -`. The trailing comment is the number of static errors that program reports.

```
# A. parents that rebuild their type from a child's #
let xs : [Int] = ["s"] in xs                                                 # 2, should be 1 #
let xs : [Int] = ["s", "t"] in xs                                            # 3, should be 2 #
let xs : [[Int]] = [[["s"]]] in xs                                           # 3, should be 1 #
let xs : [Int] = 1 :: ["s"] in xs                                            # 2, should be 1 #
let x : [Int] = [1] @ ["s"] in x                                             # 2, should be 1 #
let x : Int = 1; "s" in x                                                    # 2, should be 1 #
let x : Int = let y = "s" in y in x                                          # 2, should be 1 #
let x : poly a -> Int = typfun a -> "s" in x                                 # 2, should be 1 #
let x : Int = case 1 | 1 => "a" | _ => "b" end in x                          # 3, should be 2 #
let x : Int = case 1 | _ => let y = "s" in y end in x                        # 3, should be 1 #

# B. function parameter annotations #
let x : Int -> Int = fun (y : String) -> y in x                              # 4, should be 1 #

# C. if / case in analytic position; the extra mark prints as "(static error)" #
let x : Int = if true then "s" else 2 in x                                   # 2, should be 1 #
let x : Int = case 1 | 1 => "s" | _ => 2 end in x                            # 2, should be 1 #

# the same check in synthetic position is right, and its message is good #
let x = if true then 1 else "s" in x                                         # 1, correct #

# not in scope: parentheses, one mark per layer #
let x : Int = ("s") in x                                                     # 2, deliberate per issue 1997 #
let x : Int = ((((("s"))))) in x                                             # 6, deliberate per issue 1997 #

# fixed by PR 2502 (issues 1958 and 2507): all 1 on that branch, shown here on dev #
let x : (Int, Int) = (1, "s") in x                                           # 3 #
let x : (name=String, age=Int) = (name="a", age="b") in x                    # 4 #
let x : ((Int, Int), Int) = ((1, "s"), 2) in x                               # 5 #
let (a, b) : (Int, Int) = (1, "s") in a                                      # 3 #
let f : Int -> Bool = fun x -> x + 1 in f(1)                                 # 2 #
let f : (Int, Int) -> Int = fun (a, b) -> a in let x : Int = f(1, "s") in x  # 2 #
let x : [(Int, Int)] = [(1, "s")] in x                                       # 4 #

# already localized, for contrast #
let xs : [Int] = [1, "s", 3] in xs                                           # 1, correct #
let x : Int = "s" : Int in x                                                 # 1, correct #
let x : Int = 1 + "s" in x                                                   # 1, correct #
type T = Some(Int) + None in let x : T = Some("s") in x                      # 1, correct #

# the 2444 / 2305 interaction: two wrong elements, fewer errors than one #
let xs : [Int] = ["s", 1] in xs                                              # 1, should be 2 #
let x = [1, ""] in x                                                         # 0, should be 1 #
```

The last group is the counter-example to a naive fix: `["s", 1]` has *two* wrong elements and reports *fewer* errors than `["s"]`, because the elements do not meet each other, so the list falls back to `[?]`, which is consistent with `[Int]`, and `should_emit_nomeet_mark` drops its mark. `[1, ""]` reports nothing at all for the same reason (#2444, #2305).

**Comment by 7h3kk1d** [comment]
<img width="1070" height="1014" alt="Image" src="https://github.com/user-attachments/assets/fbe2242f-3fbd-44fa-9189-a55285ecc087" />

**Comment by 7h3kk1d** [comment]
Every example in one place, measured on `dev` at `fa6cd4eb09` with `./hazel analyze -`. The trailing comment is the number of static errors that program reports.

The whole block is one sequenced program, so it pastes in as-is. Analyzed together it reports 69 errors, and each line contributes exactly the count annotated on it — the same as running each line on its own.

```
# A. parents that rebuild their type from a child's #
let xs : [Int] = ["s"] in xs;                                                 # 2, should be 1 #
let xs : [Int] = ["s", "t"] in xs;                                            # 3, should be 2 #
let xs : [[Int]] = [[["s"]]] in xs;                                           # 3, should be 1 #
let xs : [Int] = 1 :: ["s"] in xs;                                            # 2, should be 1 #
let x : [Int] = [1] @ ["s"] in x;                                             # 2, should be 1 #
let x : Int = 1; "s" in x;                                                    # 2, should be 1 #
let x : Int = let y = "s" in y in x;                                          # 2, should be 1 #
let x : poly a -> Int = typfun a -> "s" in x;                                 # 2, should be 1 #
let x : Int = case 1 | 1 => "a" | _ => "b" end in x;                          # 3, should be 2 #
let x : Int = case 1 | _ => let y = "s" in y end in x;                        # 3, should be 1 #

# B. function parameter annotations #
let x : Int -> Int = fun (y : String) -> y in x;                              # 4, should be 1 #

# C. if / case in analytic position; the extra mark prints as "(static error)" #
let x : Int = if true then "s" else 2 in x;                                   # 2, should be 1 #
let x : Int = case 1 | 1 => "s" | _ => 2 end in x;                            # 2, should be 1 #

# the same check in synthetic position is right, and its message is good #
let x = if true then 1 else "s" in x;                                         # 1, correct #

# not in scope: parentheses, one mark per layer #
let x : Int = ("s") in x;                                                     # 2, deliberate per issue 1997 #
let x : Int = ((((("s"))))) in x;                                             # 6, deliberate per issue 1997 #

# fixed by PR 2502: all 1 on that branch, shown here on dev #
let x : (Int, Int) = (1, "s") in x;                                           # 3 #
let x : (name=String, age=Int) = (name="a", age="b") in x;                    # 4 #
let x : ((Int, Int), Int) = ((1, "s"), 2) in x;                               # 5 #
let (a, b) : (Int, Int) = (1, "s") in a;                                      # 3 #
let f : Int -> Bool = fun x -> x + 1 in f(1);                                 # 2 #
let f : (Int, Int) -> Int = fun (a, b) -> a in let x : Int = f(1, "s") in x;  # 2 #
let x : [(Int, Int)] = [(1, "s")] in x;                                       # 4 #

# already localized, for contrast #
let xs : [Int] = [1, "s", 3] in xs;                                           # 1, correct #
let x : Int = "s" : Int in x;                                                 # 1, correct #
let x : Int = 1 + "s" in x;                                                   # 1, correct #
type T = Some(Int) + None in let x : T = Some("s") in x;                      # 1, correct #

# the 2444 / 2305 interaction: two wrong elements, fewer errors than one #
let xs : [Int] = ["s", 1] in xs;                                              # 1, should be 2 #
let x = [1, ""] in x                                                          # 0, should be 1 #
```

The last group is the counter-example to a naive fix: `["s", 1]` has *two* wrong elements and reports *fewer* errors than `["s"]`, because the elements do not meet each other, so the list falls back to `[?]`, which is consistent with `[Int]`, and `should_emit_nomeet_mark` drops its mark. `[1, ""]` reports nothing at all for the same reason (#2444, #2305).
